backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/img"
public_folder: "/assets/img"

collections:
  - name: "jobs"
    label: "Job Openings"
    label_singular: "Job Opening"
    files:
      - name: "jobs-list"
        label: "Jobs List"
        file: "public/jobs.json"
        fields:
          - label: "Jobs"
            name: "jobs"
            widget: "list"
            summary: "{{fields.title}} â€” {{fields.location}}"
            fields:
              - { label: "Job ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Openings", name: "openings", widget: "number" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Place of Origin Required", name: "place_of_origin_required", widget: "boolean" }
              - { label: "Posted On", name: "posted_on", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
